fsck-on-boot can now handle failed fsck -p
If fsck returns errorlevel >= 4 (meaning, filesystem couldn't be
repaired automatically) the user is now prompted to run fsck
automatically. The user can either run fsck automatically, fix all
errors automatically (run fsck with -y), or drop to a shell to fix
things manually.

diff --git a/livekitlib b/livekitlib
--- a/livekitlib
+++ b/livekitlib
@@ -636,11 +636,40 @@ check_data_found()
 # $1 = device
 fsck_device()
 {
+   local ANSWER RETRY
    FS="$(device_tag "$1" TYPE | tr [A-Z] [a-z])"
    if [ -x /sbin/"fsck.$FS" ]; then
-       echo ""
-       echo "* Checking filesystem on $1"
-       /sbin/"fsck.$FS" -p "$1"
+      echo ""
+      echo "* Checking filesystem on $1"
+      /sbin/"fsck.$FS" -p "$1"
+      if [ $? -ge 4 ]; then
+         echo "-----------------------------------------------------------"
+         echo -n "fsck reported errors that could not "
+         echo "be automatically repaired."
+         RETRY=true
+         while $RETRY; do
+            RETRY=false
+            echo -n "Run again in interactive mode "
+            echo -n "[y]es, [n]o, fix [a]ll? "
+            read ANSWER < /dev/console
+            case $ANSWER in
+               y)
+                  /sbin/"fsck.$FS" "$1"
+                  ;;
+               a)
+                  /sbin/"fsck.$FS" -y "$1"
+                  ;;
+               n)
+                  echo "A shell will be spawned so you may effect repairs."
+                  echo "When finsihed, simply 'exit' to continue booting."
+                  /bin/sh
+                  ;;
+               *)
+                  RETRY=true
+                  ;;
+            esac
+         done
+      fi
    fi
 
    return 0
